GET http://localhost:3000/ads

###

POST http://localhost:3000/ads
Content-Type: application/json

{
  "title": "Buy this product",
  "description": "This is a great product",
  "author": "John Doe",
  "price": 100,
  "picture_url": "http://example.com/picture.jpg",
  "city": "New York"
}

###

PUT http://localhost:3000/ads/2
Content-Type: application/json

{
  "title": "Buy this product",
  "description": "This is a great product",
  "author": "Bob Mercer",
  "price": 100,
  "picture_url": "http://example.com/picture.jpg",
  "city": "Cadolive"
}

###

DELETE http://localhost:3000/ads/21

