GET http://localhost:3000/ads

###

POST http://localhost:3000/ads
Content-Type: application/json

{
  "id": 3,
  "title": "Buy this product",
  "description": "This is a great product",
  "owner": "John Doe",
  "price": 100,
  "picture": "http://example.com/picture.jpg",
  "location": "New York",
  "createdAt": "2025-05-01T00:00:00.000Z"
}

###

PUT http://localhost:3000/ads/2
Content-Type: application/json

{
  "title": "Buy this product",
  "description": "This is a great product",
  "owner": "Bob Mercer",
  "price": 100,
  "picture": "http://example.com/picture.jpg",
  "location": "New York",
  "createdAt": "2025-05-01T00:00:00.000Z"
}

###

DELETE http://localhost:3000/ads/3

